---
- hosts: localhost
  gather_facts: yes
  vars:
          region: us-east-1
  tasks:
    - name: Get Demo Instance Details
      ec2_instance_info:
        ec2_region: "{{ region }}"
        filters:
          "tag:Name": Demo3
      register: ec2_facts

    - debug:
            var: ec2_facts.instances[0].instance_id

    - name: terminate instance
      ec2:
              state: absent
              region: "{{ region }}"
              instance_id:
                      - "{{ ec2_facts.instances[0].instance_id }}"
      register: ec2

    - debug:
            var: ec2
