#This playbook creates a ec2 instance and installs git in it
- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: false

  vars:
      region: us-east-2
      instance_type: t2.micro
      ami: ami-0fc20dd1da406780b  # Redhat
      keypair: NewKey # pem file name that you download from AWS while creating a new instance

  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: "Demo"
         instance_tags:
            Name: "Demo"
      register: ec2

    - name: Add all web instance IPs to host group
      add_host: hostname={{ item.public_ip }} groupname=webservers
      with_items: '{{ ec2.instances }}'

    - name: Wait for SSH to come up
      wait_for: host={{item.public_dns_name}} port=22 delay=60 timeout=320 state=started
      with_items: '{{ec2.instances}}'
- name: Ping the instance
  hosts: webservers
  gather_facts: True
  tasks:
          - name: install git
            apt: name=git state=present
            become: yes
