---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    region: 'us-east-1'
  tasks:
    - name: Create New Key Pair with specified Keyname
      ec2_key:
        name: sshkeypairdemo
        region: us-east-1
        key_material: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"
        state: present
